import React, { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  English: {
    dashboard: "Dashboard",
    book: "Book Slot / Token",
    queue: "My Turn",
    produce: "My Produce",
    procurement: "Procurement Status",
    payments: "Payments",
    notifications: "Notifications",
    voice: "Voice Assistant",
    support: "Help & Support",
    profile: "User Profile",
    login: "Login",
    logout: "Logout",
    farmer: "Farmer Name",
    aadhaar: "Aadhaar Number",
    mobile: "Mobile Number",
    otp: "OTP",
    sendOtp: "Send OTP",
    greetingMorning: "Good Morning",
    greetingAfternoon: "Good Afternoon",
    greetingEvening: "Good Evening",
    smartProcurement: "Smart Procurement System",
    farmersAhead: "farmers ahead of you",
    estWait: "Estimated wait time",
    listenUpdate: "Listen to Update",
    leaveAt: "You should leave at",
    toReachOnTime: "to reach on time",
    distanceToCentre: "Distance to Centre",
    travelTime: "Travel Time",
    queueBuffer: "Queue Buffer",
    recArrival: "Recommended arrival",
    viewRoute: "View Route",
  },
  Hindi: {
    dashboard: "डैशबोर्ड",
    book: "स्लॉट / टोकन बुक करें",
    queue: "मेरी बारी",
    produce: "मेरी उपज",
    procurement: "खरीद की स्थिति",
    payments: "भुगतान",
    notifications: "सूचनाएं",
    voice: "आवाज़ सहायक",
    support: "सहायता और संपर्क",
    profile: "किसान प्रोफ़ाइल",
    login: "लॉगिन",
    logout: "लॉगआउट",
    farmer: "किसान का नाम",
    aadhaar: "आधार संख्या",
    mobile: "मोबाइल नंबर",
    otp: "ओटीपी",
    sendOtp: "ओटीपी भेजें",
    greetingMorning: "शुभ प्रभात",
    greetingAfternoon: "शुभ दोपहर",
    greetingEvening: "शुभ संध्या",
    smartProcurement: "स्मार्ट खरीद प्रणाली",
    farmersAhead: "किसान आपके आगे हैं",
    estWait: "अनुमानित प्रतीक्षा समय",
    listenUpdate: "अपडेट सुनें",
    leaveAt: "आपको निकलना चाहिए",
    toReachOnTime: "समय पर पहुंचने के लिए",
    distanceToCentre: "केंद्र की दूरी",
    travelTime: "यात्रा का समय",
    queueBuffer: "कतार बफर",
    recArrival: "अनुशंसित आगमन",
    viewRoute: "रास्ता देखें",
  },
  Bengali: {
    dashboard: "ড্যাশবোর্ড",
    book: "স্লট / টোকেন বুক করুন",
    queue: "আমার পালা",
    produce: "আমার ফসল",
    procurement: "সংগ্রহের স্থিতি",
    payments: "পেমেন্ট",
    notifications: "বিজ্ঞপ্তি",
    voice: "ভয়েস সহায়ক",
    support: "সহায়তা",
    profile: "কৃষক প্রোফাইল",
    login: "লগইন",
    logout: "লগআউট",
    farmer: "কৃষকের নাম",
    aadhaar: "আধার নম্বর",
    mobile: "মোবাইল নম্বর",
    otp: "ওটিপি",
    sendOtp: "ওটিপি পাঠান",
    greetingMorning: "সুপ্রভাত",
    greetingAfternoon: "শুভ অপরাহ্ন",
    greetingEvening: "শুভ সন্ধ্যা",
    smartProcurement: "স্মার্ট সংগ্রহ ব্যবস্থা",
    farmersAhead: "জন কৃষক আপনার আগে আছেন",
    estWait: "আনুমানিক অপেক্ষার সময়",
    listenUpdate: "আপডেট শুনুন",
    leaveAt: "আপনার রওনা হওয়া উচিত",
    toReachOnTime: "সময়মতো পৌঁছানোর জন্য",
    distanceToCentre: "কেন্দ্রের দূরত্ব",
    travelTime: "ভ্রমণের সময়",
    queueBuffer: "সারি বাফার",
    recArrival: "সুপারিশকৃত আগমন",
    viewRoute: "রুট দেখুন",
  },
  Marathi: {
    dashboard: "डॅशबोर्ड",
    book: "स्लॉट / टोकन बुक करा",
    queue: "माझी पाळी",
    produce: "माझे पीक",
    procurement: "खरेदी स्थिती",
    payments: "पेमेंट",
    notifications: "सूचना",
    voice: "व्हॉइस असिस्टंट",
    support: "मदत",
    profile: "शेतकरी प्रोफाइल",
    login: "लॉगिन",
    logout: "लॉगआउट",
    farmer: "शेतकऱ्याचे नाव",
    aadhaar: "आधार क्रमांक",
    mobile: "मोबाईल नंबर",
    otp: "ओटीपी",
    sendOtp: "ओटीपी पाठवा",
    greetingMorning: "शुभ प्रभात",
    greetingAfternoon: "शुभ दुपार",
    greetingEvening: "शुभ संध्याकाळ",
    smartProcurement: "स्मार्ट खरेदी प्रणाली",
    farmersAhead: "शेतकरी आपल्या पुढे आहेत",
    estWait: "अंदाजे प्रतीक्षा वेळ",
    listenUpdate: "अपडेट ऐका",
    leaveAt: "आपण निघावे",
    toReachOnTime: "वेळेवर पोहोचण्यासाठी",
    distanceToCentre: "केंद्राचे अंतर",
    travelTime: "प्रवासाचा वेळ",
    queueBuffer: "रांग बफर",
    recArrival: "शिफारस केलेले आगमन",
    viewRoute: "मार्ग पहा",
  },
  Telugu: {
    dashboard: "డాష్‌బోర్డ్",
    book: "స్లాట్ / టోకెన్ బుక్ చేయండి",
    queue: "నా వంతు",
    produce: "నా పంట",
    procurement: "సేకరణ స్థితి",
    payments: "చెల్లింపులు",
    notifications: "నోటిఫికేషన్లు",
    voice: "వాయిస్ అసిస్టెంట్",
    support: "సహాయం",
    profile: "రైతు ప్రొఫైల్",
    login: "లాగిన్",
    logout: "లాగ్ అవుట్",
    farmer: "రైతు పేరు",
    aadhaar: "ఆధార్ నంబర్",
    mobile: "మొబైల్ నంబర్",
    otp: "ఓటీపీ",
    sendOtp: "ఓటీపీ పంపండి",
    greetingMorning: "శుభోదయం",
    greetingAfternoon: "శుభ మధ్యాహ్నం",
    greetingEvening: "శుభ సాయంత్రం",
    smartProcurement: "స్మార్ట్ సేకరణ వ్యవస్థ",
    farmersAhead: "రైతులు మీ కంటే ముందున్నారు",
    estWait: "అంచనా వేసిన వేచి ఉండే సమయం",
    listenUpdate: "అప్‌డేట్ వినండి",
    leaveAt: "మీరు బయలుదేరాలి",
    toReachOnTime: "సమయానికి చేరుకోవడానికి",
    distanceToCentre: "కేంద్రానికి దూరం",
    travelTime: "ప్రయాణ సమయం",
    queueBuffer: "క్యూ బఫర్",
    recArrival: "సిఫార్సు చేసిన రాక",
    viewRoute: "మార్గం చూడండి",
  },
  Tamil: {
    dashboard: "டாஷ்போர்டு",
    book: "ஸ்லாட் / டோக்கன் பதிவு",
    queue: "என் முறை",
    produce: "என் விளைபொருள்",
    procurement: "கொள்முதல் நிலை",
    payments: "கொடுப்பனவுகள்",
    notifications: "அறிவிப்புகள்",
    voice: "குரல் உதவியாளர்",
    support: "உதவி",
    profile: "விவசாயி விவரக்குறிப்பு",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    farmer: "விவசாயி பெயர்",
    aadhaar: "ஆதார் எண்",
    mobile: "மொபைல் எண்",
    otp: "OTP",
    sendOtp: "OTP அனுப்பு",
    greetingMorning: "காலை வணக்கம்",
    greetingAfternoon: "மதிய வணக்கம்",
    greetingEvening: "மாலை வணக்கம்",
    smartProcurement: "ஸ்மார்ட் கொள்முதல் முறை",
    farmersAhead: "விவசாயிகள் உங்களுக்கு முன்னால் உள்ளனர்",
    estWait: "மதிப்பிடப்பட்ட காத்திருப்பு நேரம்",
    listenUpdate: "புதுப்பிப்பைக் கேளுங்கள்",
    leaveAt: "நீங்கள் புறப்பட வேண்டிய நேரம்",
    toReachOnTime: "நேரத்திற்கு சென்றடைய",
    distanceToCentre: "மையத்திற்கான தூரம்",
    travelTime: "பயண நேரம்",
    queueBuffer: "வரிசை தாங்கல்",
    recArrival: "பரிந்துரைக்கப்பட்ட வருகை",
    viewRoute: "பாதையைக் காண்க",
  },
  Gujarati: {
    dashboard: "ડેશબોર્ડ",
    book: "સ્લોટ / ટોકન બુક કરો",
    queue: "મારો વારો",
    produce: "મારું ઉત્પાદન",
    procurement: "ખરીદી સ્થિતિ",
    payments: "ચુકવણીઓ",
    notifications: "સૂચનાઓ",
    voice: "વોઇસ સહાયક",
    support: "સહાય",
    profile: "ખેડૂત પ્રોફાઇલ",
    login: "લોગિન",
    logout: "લોગઆઉટ",
    farmer: "ખેડૂતનું નામ",
    aadhaar: "આધાર નંબર",
    mobile: "મોબાઇલ નંબર",
    otp: "ઓટીપી",
    sendOtp: "ઓટીપી મોકલો",
    greetingMorning: "સુપ્રભાત",
    greetingAfternoon: "શુભ બપોર",
    greetingEvening: "શુભ સાંજ",
    smartProcurement: "સ્માર્ટ ખરીદ પ્રણાલી",
    farmersAhead: "ખેડૂતો તમારી આગળ છે",
    estWait: "અંદાજિત પ્રતીક્ષા સમય",
    listenUpdate: "અપડેટ સાંભળો",
    leaveAt: "તમારે નીકળવું જોઈએ",
    toReachOnTime: "સમયસર પહોંચવા માટે",
    distanceToCentre: "કેન્દ્રનું અંતર",
    travelTime: "મુસાફરી સમય",
    queueBuffer: "કતાર બફર",
    recArrival: "ભલામણ કરેલ આગમન",
    viewRoute: "માર્ગ જુઓ",
  },
  Kannada: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    book: "ಸ್ಲಾಟ್ / ಟೋಕನ್ ಬುಕ್ ಮಾಡಿ",
    queue: "ನನ್ನ ಸರದಿ",
    produce: "ನನ್ನ ಬೆಳೆ",
    procurement: "ಖರೀದಿ ಸ್ಥಿತಿ",
    payments: "ಪಾವತಿಗಳು",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    voice: "ಧ್ವನಿ ಸಹಾಯಕ",
    support: "ಸಹಾಯ",
    profile: "ರೈತರ ಪ್ರೊಫೈಲ್",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್‌ಔಟ್",
    farmer: "ರೈತರ ಹೆಸರು",
    aadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    otp: "ಒಟಿಪಿ",
    sendOtp: "ಒಟಿಪಿ ಕಳುಹಿಸಿ",
    greetingMorning: "ಶುಭೋದಯ",
    greetingAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    greetingEvening: "ಶುಭ ಸಂಜೆ",
    smartProcurement: "ಸ್ಮಾರ್ಟ್ ಸಂಗ್ರಹಣೆ ವ್ಯವಸ್ಥೆ",
    farmersAhead: "ರೈತರು ನಿಮ್ಮ ಮುಂದೆ ಇದ್ದಾರೆ",
    estWait: "ಅಂದಾಜು ಕಾಯುವ ಸಮಯ",
    listenUpdate: "ಅಪ್‌ಡೇಟ್ ಆಲಿಸಿ",
    leaveAt: "ನೀವು ಹೊರಡಬೇಕಾದ ಸಮಯ",
    toReachOnTime: "ಸಮಯಕ್ಕೆ ತಲುಪಲು",
    distanceToCentre: "ಕೇಂದ್ರದ ದೂರ",
    travelTime: "ಪ್ರಯಾಣದ ಸಮಯ",
    queueBuffer: "ಕ್ಯೂ ಬಫರ್",
    recArrival: "ಶಿಫಾರಸು ಮಾಡಿದ ಆಗಮನ",
    viewRoute: "ಮಾರ್ಗವನ್ನು ವೀಕ್ಷಿಸಿ",
  },
  Malayalam: {
    dashboard: "ഡാഷ്ബോർഡ്",
    book: "സ്ലോട്ട് / ടോക്കൺ ബുക്ക് ചെയ്യുക",
    queue: "എന്റെ ഊഴം",
    produce: "എന്റെ വിളവ്",
    procurement: "സംഭരണ ​​സ്ഥിതി",
    payments: "പേയ്‌മെന്റുകൾ",
    notifications: "അറിയിപ്പുകൾ",
    voice: "വോയ്‌സ് അസിസ്റ്റന്റ്",
    support: "സഹായം",
    profile: "കർഷക പ്രൊഫൈൽ",
    login: "ലോഗിൻ",
    logout: "ലോഗൗട്ട്",
    farmer: "കർഷകന്റെ പേര്",
    aadhaar: "ആധാർ നമ്പർ",
    mobile: "മൊബൈൽ നമ്പർ",
    otp: "ഒടിപി",
    sendOtp: "ഒടിപി അയയ്ക്കുക",
    greetingMorning: "സുപ്രഭാതം",
    greetingAfternoon: "ശുഭ ഉച്ചതിരിഞ്ഞ്",
    greetingEvening: "ശുഭ സായാഹ്നം",
    smartProcurement: "സ്മാർട്ട് സംഭരണ ​​സംവിധാനം",
    farmersAhead: "കർഷകർ നിങ്ങളുടെ മുന്നിലുണ്ട്",
    estWait: "കണക്കാക്കിയ കാത്തിരിപ്പ് സമയം",
    listenUpdate: "അപ്‌ഡേറ്റ് കേൾക്കുക",
    leaveAt: "നിങ്ങൾ പുറപ്പെടേണ്ട സമയം",
    toReachOnTime: "സമയത്ത് എത്തിച്ചേരാൻ",
    distanceToCentre: "കേന്ദ്രത്തിലേക്കുള്ള ദൂരം",
    travelTime: "യാത്രാ സമയം",
    queueBuffer: "ക്യൂ ബഫർ",
    recArrival: "ശുപാർശ ചെയ്യുന്ന വരവ്",
    viewRoute: "റൂട്ട് കാണുക",
  },
  Punjabi: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    book: "ਸਲਾਟ / ਟੋਕਨ ਬੁੱਕ ਕਰੋ",
    queue: "ਮੇਰੀ ਵਾਰੀ",
    produce: "ਮੇਰੀ ਉਪਜ",
    procurement: "ਖਰੀਦ ਸਥਿਤੀ",
    payments: "ਭੁਗਤਾਨ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    voice: "ਆਵਾਜ਼ ਸਹਾਇਕ",
    support: "ਸਹਾਇਤਾ",
    profile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ",
    login: "ਲੌਗਇਨ",
    logout: "ਲੌਗਆਉਟ",
    farmer: "ਕਿਸਾਨ ਦਾ ਨਾਮ",
    aadhaar: "ਆਧਾਰ ਨੰਬਰ",
    mobile: "ਮੋਬਾਈਲ ਨੰਬਰ",
    otp: "ਓਟੀਪੀ",
    sendOtp: "ਓਟੀਪੀ ਭੇਜੋ",
    greetingMorning: "ਸ਼ੁਭ ਸਵੇਰ",
    greetingAfternoon: "ਸ਼ੁਭ ਦੁਪਹਿਰ",
    greetingEvening: "ਸ਼ੁਭ ਸ਼ਾਮ",
    smartProcurement: "ਸਮਾਰਟ ਖਰੀਦ ਪ੍ਰਣਾਲੀ",
    farmersAhead: "ਕਿਸਾਨ ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਹਨ",
    estWait: "ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ",
    listenUpdate: "ਅੱਪਡੇਟ ਸੁਣੋ",
    leaveAt: "ਤੁਹਾਨੂੰ ਨਿਕਲਣਾ ਚਾਹੀਦਾ ਹੈ",
    toReachOnTime: "ਸਮੇਂ ਸਿਰ ਪਹੁੰਚਣ ਲਈ",
    distanceToCentre: "ਕੇਂਦਰ ਦੀ ਦੂਰੀ",
    travelTime: "ਯਾਤਰਾ ਦਾ ਸਮਾਂ",
    queueBuffer: "ਕਤਾਰ ਬਫਰ",
    recArrival: "ਸਿਫ਼ਾਰਸ਼ੀ ਪਹੁੰਚ",
    viewRoute: "ਰਸਤਾ ਦੇਖੋ",
  },
  Odia: {
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    book: "ସ୍ଲଟ୍ / ଟୋକନ୍ ବୁକ୍ କରନ୍ତୁ",
    queue: "ମୋ ପାଳି",
    produce: "ମୋ ଉତ୍ପାଦନ",
    procurement: "ସଂଗ୍ରହ ସ୍ଥିତି",
    payments: "ଦେୟ",
    notifications: "ବିଜ୍ଞପ୍ତି",
    voice: "ଭଏସ୍ ସହାୟକ",
    support: "ସାହାଯ୍ୟ",
    profile: "କୃଷକ ପ୍ରୋଫାଇଲ୍",
    login: "ଲଗଇନ୍",
    logout: "ଲଗଆଉଟ୍",
    farmer: "ଚାଷୀଙ୍କ ନାମ",
    aadhaar: "ଆଧାର ନମ୍ବର",
    mobile: "ମୋବାଇଲ୍ ନମ୍ବର",
    otp: "ଓଟିପି",
    sendOtp: "ଓଟିପି ପଠାନ୍ତୁ",
    greetingMorning: "ସୁପ୍ରଭାତ",
    greetingAfternoon: "ଶୁଭ ଅପରାହ୍ନ",
    greetingEvening: "ଶୁଭ ସନ୍ଧ୍ୟା",
    smartProcurement: "ସ୍ମାର୍ଟ ସଂଗ୍ରହ ପ୍ରଣାଳୀ",
    farmersAhead: "ଜଣ ଚାଷୀ ଆପଣଙ୍କ ଆଗରେ ଅଛନ୍ତି",
    estWait: "ଆନୁମାନିକ ଅପେକ୍ଷା ସମୟ",
    listenUpdate: "ଅପଡେଟ୍ ଶୁଣନ୍ତୁ",
    leaveAt: "ଆପଣ ବାହାରିବା ଉଚିତ",
    toReachOnTime: "ସମୟରେ ପହଞ୍ଚିବା ପାଇଁ",
    distanceToCentre: "କେନ୍ଦ୍ରର ଦୂରତା",
    travelTime: "ଯାତ୍ରା ସମୟ",
    queueBuffer: "ଧାଡ଼ି ବଫର",
    recArrival: "ସୁପାରିଶ କରାଯାଇଥିବା ଆଗମନ",
    viewRoute: "ମାର୍ଗ ଦେଖନ୍ତୁ",
  },
  Assamese: {
    dashboard: "ড্যাশব’ৰ্ড",
    book: "স্লট / টোকেন বুক কৰক",
    queue: "মোৰ পালি",
    produce: "মোৰ শস্য",
    procurement: "ক্ৰয়ৰ অৱস্থা",
    payments: "পৰিশোধ",
    notifications: "জাননী",
    voice: "ভয়েচ সহায়ক",
    support: "সহায়",
    profile: "কৃষক প্ৰফাইল",
    login: "লগইন",
    logout: "লগআউট",
    farmer: "কৃষকৰ নাম",
    aadhaar: "আধাৰ নম্বৰ",
    mobile: "মোবাইল নম্বৰ",
    otp: "অ’টিপি",
    sendOtp: "অ’টিপি পঠিয়াওক",
    greetingMorning: "সুপ্ৰভাত",
    greetingAfternoon: "শুভ আবেলি",
    greetingEvening: "শুভ সন্ধ্যা",
    smartProcurement: "স্মাৰ্ট ক্ৰয় প্ৰণালী",
    farmersAhead: "গৰাকী কৃষক আপোনাৰ আগত আছে",
    estWait: "আনুমানিক অপেক্ষাৰ সময়",
    listenUpdate: "আপডেট শুনক",
    leaveAt: "আপুনি ওলোৱা উচিত",
    toReachOnTime: "সময়মতে উপনীত হ’বলৈ",
    distanceToCentre: "কেন্দ্ৰৰ দূৰত্ব",
    travelTime: "যাত্ৰাৰ সময়",
    queueBuffer: "শাৰী বাফাৰ",
    recArrival: "পৰামৰ্শিত আগমন",
    viewRoute: "পথ চাওক",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem("kisanLanguage") || "English";
  });

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLanguageState(newLang);
      localStorage.setItem("kisanLanguage", newLang);
    }
  };

  const t = translations[language] || translations.English;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, supportedLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
